language: node_js
node_js:
    - "0.10"
services:
    - mongodb
before_script:
    - sleep 15
    - ./tests/setup.js
env:
    global:
        - "LOCAL_USER=test@test.com"
        - "LOCAL_PWD=test123"
        - "GITHUB_USER=test2@test.com"
        - "USED_USER=test3@test.com"
        - "USED_PWD=test123"
        - "DATABASE=test"
        - "DB_USER=sessionHandler"
        - "DB_PWD=supersecretpassword"
        - "USER_ADMIN=sessionHandler"
        - "USER_ADMIN_PWD=supersecretpassword"
